### ISSUE TITLE
Bug: Issue with Demo Application link

### ISSUE THREAD

**Issue by tushar-prox** [dyte-io/async-interview#1]
# 🐛 Issue  

Link mentioned in the about section is https://async-interview.vercel.app/

![Screenshot_2023-10-26_at_12_13_13_PM](https://github.com/dyte-io/async-interview/assets/76202617/e1299ab5-d175-4169-ad13-813291bdcd8b)

This link is throwing 404 
![Screenshot 2023-10-26 at 12 13 05 PM](https://github.com/dyte-io/async-interview/assets/76202617/575de855-1a45-4c16-ad28-2ee6e914b82c)

# ⚙️ Fix  
As per blog, this link should be https://dyte-async-interview.vercel.app/

**Comment by vaibhavshn** [comment]
Thanks for reporting!

Looks like we changed the domain after deployment and old URL was left behind. Fixed it.
